BEST THING EVER
Seboeb-test/test-repo pull request #1
Opened 2018-06-21 19:09 UTC by Seboeb

2018-06-21 19:11 UTC, Seboeb-test reviewed
Hmm ja hnoor ik vind het beetje raar, kan je even heir op terug komen?

2018-06-21 19:12 UTC, Seboeb-test commented
dit werkkt niet toch

2018-06-21 19:12 UTC, Seboeb-test reviewed
dit werkt wel toch

2018-06-21 19:20 UTC, Seboeb-test requested changes
Kan je dit veranderen?

2018-06-21 19:23 UTC, Seboeb-test reviewed
nu is gewoon comment

2018-06-21 19:24 UTC, Seboeb-test approved these changes

2018-06-21 19:26 UTC, Seboeb-test approved these changes
ja hoor approve weer

2018-06-22 09:16 UTC, Seboeb-test reviewed
Ja ja nu moet het gebuerne hoor, integratie!!

2018-06-22 09:20 UTC, Seboeb-test reviewed
asdfasf

2018-06-22 09:26 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 09:30 UTC, Seboeb-test reviewed
asdasdf

2018-06-22 09:31 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 09:33 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 09:34 UTC, Seboeb-test reviewed
asdfasf

2018-06-22 09:35 UTC, Seboeb-test reviewed
asdfasdfasdfasdf

2018-06-22 09:37 UTC, Seboeb-test reviewed
asdfasdfasdfasdfasdf

2018-06-22 09:40 UTC, Seboeb-test reviewed
oijaonvueos

2018-06-22 09:42 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 09:43 UTC, Seboeb-test reviewed
asdfasdfasdfasf

2018-06-22 09:47 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 09:49 UTC, Seboeb-test reviewed
asd

2018-06-22 10:40 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 10:50 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 10:53 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 10:54 UTC, Seboeb-test reviewed
as

2018-06-22 10:54 UTC, Seboeb-test reviewed
pfff

2018-06-22 11:19 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 11:20 UTC, Seboeb-test reviewed
Ik vind he maar kankerzooi

2018-06-22 11:43 UTC, Seboeb-test reviewed
asdfasf

2018-06-22 12:15 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 12:49 UTC, Seboeb-test reviewed
asdfandfl;

2018-06-22 13:05 UTC, Seboeb-test reviewed
Deze comment moet in jira verschijnen

2018-06-22 13:05 UTC, Seboeb-test reviewed
Deze comment is een test

2018-06-22 13:08 UTC, Seboeb-test reviewed
Deze comment moet in jira terecht komen.

2018-06-22 13:09 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 13:12 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 13:13 UTC, Seboeb-test reviewed
Deze comment moet nu in jira komen

2018-06-22 13:16 UTC, Seboeb-test reviewed
asdfasdf

2018-06-22 13:17 UTC, Seboeb-test reviewed
Laat deze comment nu wel werken bitte

2018-06-22 13:18 UTC, Seboeb-test reviewed
Fingers crossed!! \o/

2018-06-22 13:30 UTC, Seboeb-test reviewed
Dit wordt fantastisch!!!!!! 8====D~~~~~

2018-06-22 13:32 UTC, Seboeb-test reviewed
@bryan hiuyituidryustu

2018-06-25 08:35 UTC, Seboeb reviewed
Deze test moet werken

2018-06-25 08:52 UTC, Seboeb reviewed
Dit is weer een comment

2018-06-25 08:54 UTC, Seboeb reviewed
what is going to happen now

2018-06-25 08:56 UTC, Seboeb reviewed
Deze moet heel mooi zijn

2018-06-25 08:57 UTC, Seboeb reviewed
Deze moet dan heel mooi zijn

2018-06-25 09:01 UTC, Seboeb reviewed
Dit moet nog mooier zijn dan daarnet. Ik ben benieuwd hoe hij zal reageren als dit een wat langere tekst is.

2018-06-25 09:04 UTC, Seboeb reviewed
En hoe zit dit er dan nu uit?

2018-06-25 09:06 UTC, Seboeb reviewed
asdfhjaosij jlkfjal ij fois soijf osijd oijsodifj osijfosdjf oisjf oij akd lkfj woijlsidjf oisj sdli sdf

2018-06-25 09:06 UTC, Seboeb reviewed
Dit moet nog mooier zijn dan daarnet. Ik ben benieuwd hoe hij zal reageren als dit een wat langere tekst is.

2018-06-25 09:08 UTC, merged